### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xen-api#1]
It seems that XML-RPC decoding is very heavy and block the event loop for a long time.

This can be seen by enabling the debug in the CLI:

``` javascript
> DEBUG=xen-api:perf xen-api xen1.company.net root
Password: ******
xen1.company.net>   xen-api:perf blocked for 1797ms +0ms
  xen-api:perf blocked for 718ms +820ms
```

**Leads:**
1. using JSON encoded values in XML-RPC
   - <del>implemented in the [xmlrpc-json branch](/julien-f/js-xen-api/tree/xmlrpc-json)</del> **merged in [master](/julien-f/js-xen-api)**
   - faster (4x) but still has some perf issues
   - XAPI JSON serialization is a bit buggy and may leads to issues
2. using a native XML parser [xmlrpc#expat](/julien-f/node-xmlrpc/tree/expat)
   - implemented in the [xmlrpc-expat branch](/julien-f/js-xen-api/tree/xmlrpc-expat)
   - <del>faster (3x) but still has some perf issues</del>
   - latest data indicate little improvements over **1** (50%)
   - native addons can cause deployment issues
3. using JSON-RPC (version 1)
   - implemented in the [json-rpc branch](/julien-f/js-xen-api/tree/json-rpc)
   - requires Xen Server 7 (Dundee)
   - should be fast enough
4. throttling events
   - there is no need for high latency sync, a delay of 250/500ms would be acceptable
   - less data to parse (deduplication)
   - less HTTP requests
   - better JSON/XML ratio
   - BUT less and bigger events can reduce the reactive of the Node process

**Comment by julien-f** [comment]
I think **1** is safe enough to be merged to master once validated with legacy Xen Server version.

For **2**, it should be determined if it still improves perfs on top of **1*.

**Comment by olivierlambert** [comment]
Using **3** if possible, then fallback on **1**.

**Comment by julien-f** [comment]
This issue was moved to vatesfr/xo-web#2407
