### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by phoomin2012** [vatesfr/xen-api#72]
I got this error when I run test in my computer.

> { Error: self signed certificate
>     at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
>     at emitNone (events.js:105:13)
>     at TLSSocket.emit (events.js:207:7)
>     at TLSSocket._finishInit (_tls_wrap.js:628:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
>   code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
>   method: 'session.login_with_password' }

XenServer 7.2 in VirtualBox
MacBook Air 2014

**Comment by julien-f** [comment]
If your XenServer has a self-signed certificate you have two options:
- use HTTP (`url: 'https://xen1.company.net'`)
- explicitly allow them (`allowUnauthorized: true`)
